services:
  photograph-backend:
    build: .
    expose:
      - "58058"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.photograph.rule=Host(`photograph.motizuki.dev`)"
      - "traefik.http.routers.photograph.entrypoints=websecure"
      - "traefik.http.routers.photograph.tls=true"
      - "traefik.http.services.photograph.loadbalancer.server.port=58058"
